### ISSUE TITLE
About Stable Diffusion-Turbo

### ISSUE THREAD

**Issue by VillainPrime** [GaParmar/img2img-turbo#110]
Thank you very much for this excellent work, which has been very helpful and inspiring to me.
I don't have enough knowledge about image processing models, so I would like to ask a question.
The Stable Diffusion-Turbo link in your project seems to be invalid. It may be because of this that the model I configured in Colab before cannot run. Is there any way to solve this problem?
I would be very grateful if you can give me some guidance.

**Comment by Vigneshwar73** [comment]
Hey! I am getting an invalid link error. Did you solve it?

**Comment by GaParmar** [comment]
This is likely a network connection issue.
