### ISSUE TITLE
Error with gradio_canny2image.py

### ISSUE THREAD

**Issue by SoftologyPro** [GaParmar/img2img-turbo#2]
```
Img2Img Turbo\src\pix2pix_turbo.py", line 93, in __init__
    vae_lora_config = LoraConfig(r=sd["rank_vae"], init_lora_weights="gaussian", target_modules=sd["vae_lora_target_modules"])
UnboundLocalError: local variable 'sd' referenced before assignment
```

**Comment by GaParmar** [comment]
Seems like the model state dict was not found correctly. 
Could you tell me the bash command you used when you encountered this error?

**Comment by GaParmar** [comment]
did you pass in a `--model` flag?

**Comment by SoftologyPro** [comment]
No, what is the full commandline I should use?

**Comment by GaParmar** [comment]
You could try this example command:

> python src/inference_paired.py --model "edge_to_image" \
>     --input_image "assets/bird.png" \
>     --prompt "a blue bird" \
>     --output_dir "outputs"

**Comment by GaParmar** [comment]
Thanks for pointing out this bug, it should be resolved now!
There was a typo in the naming of the model.

**Comment by SoftologyPro** [comment]
Thanks for the quick fix.  Works fine now.
