### ISSUE TITLE
CUDA out of memory on unpaired cyclegan-turbo training

### ISSUE THREAD

**Issue by YingJGuo** [GaParmar/img2img-turbo#32]
How much GPU memory is required to train cyclegan-turbo?
When i tried to train with a single RTX4090 (24GB),  it failed with CUDA OUT OF MEMORY.
Can I change any parameters to relieve the requirement of gpu memory ?

**Comment by King-HAW** [comment]
You can try the mixed precision training, check my update here (https://github.com/King-HAW/img2img-turbo), it works on 24GB GPU with setting batchsize to 1.

**Comment by YingJGuo** [comment]
> You can try the mixed precision training, check my update here (https://github.com/King-HAW/img2img-turbo), it works on 24GB GPU with setting batchsize to 1.

Thanks for your reply! I will try it.

**Comment by Gao3chen** [comment]
> You can try the mixed precision training, check my update here (https://github.com/King-HAW/img2img-turbo), it works on 24GB GPU with setting batchsize to 1.

how do you set the "accelerate config"?

**Comment by zhangsngood** [comment]
> You can try the mixed precision training, check my update here (https://github.com/King-HAW/img2img-turbo), it works on 24GB GPU with setting batchsize to 1.

Hello, thank you for your great work. If I want to implement multi-GPU inference, which parts should I modify?

**Comment by Aaron-116** [comment]
> You can try the mixed precision training, check my update here (https://github.com/King-HAW/img2img-turbo), it works on 24GB GPU with setting batchsize to 1.

Hello, I’m also deploying cyclegan_turbo on an RTX 4090, and I ran into a CUDA out of memory issue as well. I used the following settings:
```
--train_img_prep "resize_256" --val_img_prep "no_resize" \
--learning_rate="1e-5" --max_train_steps=25000 \
--train_batch_size=1 --gradient_accumulation_steps=1 \
--report_to "wandb" --tracker_project_name "gparmar_unpaired_h2z_cycle_debug_v2" \
--enable_xformers_memory_efficient_attention --validation_steps 250 \
--lambda_gan 0.5 --lambda_idt 1 --lambda_cycle 1
```
And I use fp16 as mixed precison.
May I ask how exactly you configured yours?
