### ISSUE TITLE
Text prompt for diffusion models?

### ISSUE THREAD

**Issue by ShenZheng2000** [GaParmar/img2img-turbo#40]
Which **text prompt** and **seed** are you utilizing for other diffusion models like InstructPix2Pix?

**text prompt**
'driving in the night' aligns with Fig. 2, while 'day to night' or 'day2night' are indicated by the tables. Therefore, I am unsure about which one to use. 

**seed**
InstructPix2Pix operates with a random seed, and altering it significantly impacts the output image. Thus, knowing the precise seed employed for the reported result is crucial.

**Comment by GaParmar** [comment]
Hi, 

**text prompt** We use the following text prompt for instruct-pix2pix for the day to night translation.
`turn this into a night driving scene`

**seed** We use `seed=42` across all baselines and experiments

-Gaurav

**Comment by ShenZheng2000** [comment]
Thanks!
