### ISSUE TITLE
JSON loading is broken on custom dataset

### ISSUE THREAD

**Issue by DrBrule** [GaParmar/img2img-turbo#52]
Hi, Interesting project! 

I'm trying to do a pix2pix-turbo training run but the JSON loading is not working for me. Frankly, I don't even want to use prompts, I want a pure A to B domain transfer.  So I've created a JSON file with the following structure:
```
{"source":"trainA/1155.png","target":"trainB/1155.png","prompt":"full design"}
{"source":"trainA/1850.png","target":"trainB/1850.png","prompt":"full design"}
{"source":"trainA/1278.png","target":"trainB/1278.png","prompt":"full design"}
```

Near as I can tell, that's identical to the prompts.json made for the demo 
```
{"source": "source/0.png", "target": "target/0.png", "prompt": "pale golden rod circle with old lace background"}
{"source": "source/1.png", "target": "target/1.png", "prompt": "light coral circle with white background"}
{"source": "source/2.png", "target": "target/2.png", "prompt": "aqua circle with light pink background"}
```

but when I try the training script, I get errors about the JSON Decoding.  
```
  File "/home/oem/coding/anaconda3/envs/img2img-turbo/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 114)

```

I need my output to be pixel-accurate to my inputs, so using the Paired Dataset is important to me ( I think) 

A: What is wrong with my JSON file???
B: Is there a way to disable the JSON requirement for paired data?

**Comment by aihacker111** [comment]
Your json format is not correct 
It should be like this for pix2pix-turbo task
{
    "000000203564.jpg": "a clock with the appearance of the wheel of a bicycle",
    "000000322141.jpg": "a bathroom with walls that are painted baby blue",
    "000000016977.jpg": "a couple of cars parked in a busy street sidewalk",
    "000000106140.jpg": "a passenger plane taking off into the sky",
    "000000571635.jpg": "bathroom containing a toilet a sink and a wicker basket",
    "000000301837.jpg": "a room that has a stove and a icebox in it",
    "000000315702.jpg": "a bathroom sink cluttered with multiple personal care items",
    "000000189634.jpg": "an open box contains an unknown purple object",
    "000000472598.jpg": "an antique turquoise car is parked at the curb",
    "000000162113.jpg": "a kitchen with a stove sick and dishes",
    "000000126657.jpg": "a group of motorcycles drive down a city street",
    "000000285421.jpg": "a cat is drinking water out of a toilet",
    }
    You don't need to add target path because the image name is the same, follow this will fixed your issues 
    Good Luck !

**Comment by DrBrule** [comment]
Perfect, thanks for your help!

**Comment by 9ww1** [comment]
Excuse me, I don't need JSON file prompts either. I would like to ask how you handled it. I would like to learn from it . Thank you very much

> Hi, Interesting project!
> 
> I'm trying to do a pix2pix-turbo training run but the JSON loading is not working for me. Frankly, I don't even want to use prompts, I want a pure A to B domain transfer. So I've created a JSON file with the following structure:
> 
> ```
> {"source":"trainA/1155.png","target":"trainB/1155.png","prompt":"full design"}
> {"source":"trainA/1850.png","target":"trainB/1850.png","prompt":"full design"}
> {"source":"trainA/1278.png","target":"trainB/1278.png","prompt":"full design"}
> ```
> 
> Near as I can tell, that's identical to the prompts.json made for the demo
> 
> ```
> {"source": "source/0.png", "target": "target/0.png", "prompt": "pale golden rod circle with old lace background"}
> {"source": "source/1.png", "target": "target/1.png", "prompt": "light coral circle with white background"}
> {"source": "source/2.png", "target": "target/2.png", "prompt": "aqua circle with light pink background"}
> ```
> 
> but when I try the training script, I get errors about the JSON Decoding.
> 
> ```
>   File "/home/oem/coding/anaconda3/envs/img2img-turbo/lib/python3.10/json/decoder.py", line 340, in decode
>     raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 114)
> ```
> 
> I need my output to be pixel-accurate to my inputs, so using the Paired Dataset is important to me ( I think)
> 
> A: What is wrong with my JSON file??? B: Is there a way to disable the JSON requirement for paired data?

Excuse me, I don't need JSON file prompts either. I would like to ask how you handled it. I would like to learn from it and learn from it. Thank you very much!

**Comment by DrBrule** [comment]
The other comment in this thread from @aihacker111  sorted it out for me.  You don't need to include the full path, as the datasets are paired, just the name of the file and the code interprets the path from there.  Then you can just use the same prompt for everything!

**Comment by 9ww1** [comment]
> {"source":"trainA/1155.png","target":"trainB/1155.png","prompt":"full design"}
> {"source":"trainA/1850.png","target":"trainB/1850.png","prompt":"full design"}
> {"source":"trainA/1278.png","target":"trainB/1278.png","prompt":"full design"}
Thank you very much for your reply! I understand the correct format of the JSON file, but since I only want to use the paired dataset for training, there is no need for prompt text information. I noticed that in your question, the "prompt" field has a value of "full design". Can I also adopt this value in my task? Perhaps it can be directly set to empty？

**Comment by DrBrule** [comment]
You can set it to anything, I believe you could even set it to a single whitespace ( " " ) if it needs to retain the exact file:prompt JSON format.
