### ISSUE TITLE
Problem of downloading pretrained model weight

### ISSUE THREAD

**Issue by RunkunL** [GaParmar/img2img-turbo#66]
Thank you for your excellent work！I'm having issues with my network connection while downloading a pretrained model. If I manually download the weight file from the hugging face website, where should I put it?

**Comment by GaParmar** [comment]
Hi, 

Thank you for your interest in this project! Could you tell me which file / pre-trained model you're trying to run? 

-Gaurav

**Comment by RunkunL** [comment]
Thank you for your reply. I checked huggingface's tutorial about offline models. After I downloaded the model, I specified the model loading path and it ran successfully.😄
