### ISSUE TITLE
float16

### ISSUE THREAD

**Issue by qqaapp** [GaParmar/img2img-turbo#71]
How to modify float16 inference.

**Comment by GaParmar** [comment]
Hi, 

Thank you for your interest in the project!
Try using the flag "--use_fp16" with the `src/inference_paired.py` inference command.
Or if you have a custom inference script, you can just cast the model to fp16 with a command like `model.half()`.
See the relevant line [here](https://github.com/GaParmar/img2img-turbo/blob/main/src/inference_paired.py#L35).

-Gaurav
