### ISSUE TITLE
Differents results for eval images when running inference

### ISSUE THREAD

**Issue by Akos15** [GaParmar/img2img-turbo#81]
Hello,
First, thank you for your  work. I am currently fine-tuning the CycleGAN Turbo model to generate infrared images (day → infrared). I've successfully trained the model, and as part of the `train_cyclegan_turbo.py` file, we're performing inference on the evaluation data to compute the FID and Dino struct metrics, and the output images are saved. I have tried to reproduce the same results (eval images output) using the "unpaired_infrared.py" file but unfortunately, the outputs are differenets. Do you know how to fix it ?

**Comment by GaParmar** [comment]
In what ways are the outputs different? 
Could you also share what the `unpaired_infrared.py` file looks like? 

-Gaurav

**Comment by loveberryc** [comment]
Hello, can you share how you solved this, I also found the results different from the fake_b results saved during training when executing unpaired_infrared.py.

**Comment by loveberryc** [comment]
Hello, can you share how you solved this, I also found the results different from the fake_b results saved during training when executing inference_unpaired.py.

**Comment by bakisanlan** [comment]
I solve the problem with giving exact prompt name as input with my 'fixed_promt_a.txt'. For example if I choose direction as 'a2b', I have to use '--prompt "fixed_prompt_a.txt"
